HOSTED_IP     ="localhost:8080"
SA_HOSTED_IP  ="localhost:8080"
BASE_URL      ="http://"+HOSTED_IP+"/v1/rest"
SEARCH_END    ="http://search-jaldeetest-aic4hfc23lkmjsm5qtqklyanrq.ap-southeast-1.cloudsearch.amazonaws.com"
S3_URL        ="https://s3-us-west-1.amazonaws.com/ynwlocal.youneverwait.com"
SA_BASE_URL     = "http://"+SA_HOSTED_IP+"/superadmin/rest"
