HOSTED_IP     ="scale.jaldee.com"
SA_HOSTED_IP  ="sascale.jaldee.com"
BASE_URL      ="https://"+HOSTED_IP+"/v1/rest"
SEARCH_END    ="https://search-jaldeescale-ed3vsjknk7eplc7erfxdhj3764.ap-southeast-1.cloudsearch.amazonaws.com"
S3_URL        ="http://s3.ap-south-1.amazonaws.com/scale.jaldee.com"
SA_BASE_URL     = "https://"+SA_HOSTED_IP+"/superadmin/rest"
ENVIRONMENT   ="scale"
